'use client'
import { useEffect,useMemo,useState } from 'react'
import { createUserWithEmailAndPassword,getRedirectResult,GoogleAuthProvider,onAuthStateChanged,sendEmailVerification,signInWithEmailAndPassword,signInWithPopup,signInWithRedirect,signOut as firebaseSignOut,updateProfile,type User } from 'firebase/auth'
import { doc,getDoc,setDoc } from 'firebase/firestore'
import { firebaseAuth,firebaseDb,isFirebaseConfigured } from './firebaseClient'
import { isValidRole,normalizeRole,type Role } from './roles'
export type AuthUser={id:string;email:string;displayName:string;role?:Role;operationalRole?:string;demo:boolean;emailVerified?:boolean;photoURL?:string}
const PREVIEW='afrigo:preview-session'
const preview=()=>{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(PREVIEW)||'null')as AuthUser|null}catch{return null}}
async function fromFirebase(user:User):Promise<AuthUser>{let role:Role|undefined,operationalRole:string|undefined;if(firebaseDb){const snap=await getDoc(doc(firebaseDb,'users',user.uid));role=normalizeRole(snap.data()?.role)||undefined;operationalRole=snap.data()?.operationalRole||undefined}return{id:user.uid,email:user.email||'',displayName:user.displayName||user.email?.split('@')[0]||'Afrigo user',role,operationalRole,demo:false,emailVerified:user.emailVerified,photoURL:user.photoURL||undefined}}
export async function signUp({firstName,lastName,email,password}:{firstName:string;lastName:string;email:string;password:string}){if(!firebaseAuth||!firebaseDb)throw new Error('Firebase Authentication is not configured.');const displayName=`${firstName.trim()} ${lastName.trim()}`.trim();if(!displayName||!email.trim()||password.length<8)throw new Error('Enter your name, a valid email, and a password of at least 8 characters.');const credential=await createUserWithEmailAndPassword(firebaseAuth,email.trim().toLowerCase(),password);await updateProfile(credential.user,{displayName});await setDoc(doc(firebaseDb,'users',credential.user.uid),{email:credential.user.email,displayName,role:null,createdAt:new Date(),updatedAt:new Date()});let needsVerification=false;try{await sendEmailVerification(credential.user);needsVerification=true}catch{}return{user:await fromFirebase(credential.user),needsVerification}}
export async function signIn({email,password}:{email:string;password:string}){if(!firebaseAuth)throw new Error('Firebase Authentication is not configured.');const result=await signInWithEmailAndPassword(firebaseAuth,email.trim().toLowerCase(),password);return fromFirebase(result.user)}
async function upsertProviderUser(user:User){if(!firebaseDb)throw new Error('Firebase is not configured.');const ref=doc(firebaseDb,'users',user.uid),existing=await getDoc(ref);await setDoc(ref,{email:user.email,displayName:user.displayName||user.email?.split('@')[0]||'AfriGoOS user',photoURL:user.photoURL||null,updatedAt:new Date(),...(existing.exists()?{}:{role:null,createdAt:new Date()})},{merge:true});return fromFirebase(user)}
// Popup is the primary flow: redirect sign-in breaks on browsers that block third-party storage when the app is not served from the Firebase auth domain. Redirect is only a fallback when popups are unavailable.
export async function signInWithGoogle():Promise<AuthUser|null>{if(!firebaseAuth||!firebaseDb)throw new Error('Firebase Authentication is not configured.');const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{const result=await signInWithPopup(firebaseAuth,provider);return upsertProviderUser(result.user)}catch(error:any){if(error?.code==='auth/popup-blocked'||error?.code==='auth/operation-not-supported-in-this-environment'){await signInWithRedirect(firebaseAuth,provider);return null}throw error}}
export async function completeRedirectSignIn(){if(!firebaseAuth)return null;const result=await getRedirectResult(firebaseAuth);return result?upsertProviderUser(result.user):null}
const AUTH_ERRORS:Record<string,string>={'auth/invalid-credential':'That email and password combination is not correct.','auth/wrong-password':'That email and password combination is not correct.','auth/user-not-found':'That email and password combination is not correct.','auth/invalid-email':'Enter a valid email address.','auth/email-already-in-use':'An account already exists for this email. Sign in instead.','auth/weak-password':'Choose a stronger password of at least 8 characters.','auth/too-many-requests':'Too many attempts. Wait a few minutes, then try again.','auth/network-request-failed':'Network problem. Check your connection and try again.','auth/account-exists-with-different-credential':'This email is registered with a password. Sign in with email and password.','auth/unauthorized-domain':'Google sign-in is not enabled for this domain yet.','auth/user-disabled':'This account has been disabled. Contact support.'}
export function authErrorMessage(error:any,fallback='Something went wrong. Please try again.'){if(error?.code==='auth/popup-closed-by-user'||error?.code==='auth/cancelled-popup-request')return '';return AUTH_ERRORS[error?.code]||error?.message||fallback}
export async function requestEmailVerification(){if(!firebaseAuth?.currentUser)throw new Error('Sign in before requesting verification.');if(firebaseAuth.currentUser.emailVerified)return;await sendEmailVerification(firebaseAuth.currentUser)}
export function createDemoSession(role:string){if(!isValidRole(role))throw new Error('Invalid preview role.');const user:AuthUser={id:`preview-${role.toLowerCase()}`,email:`preview+${role.toLowerCase()}@afrigo.local`,displayName:`${role} preview`,role,demo:true};localStorage.setItem(PREVIEW,JSON.stringify(user));window.dispatchEvent(new Event('afrigo-auth-change'));return user}
export async function updateRole(role:string){if(!isValidRole(role))throw new Error('Invalid role.');const p=preview();if(p){const updated={...p,role};localStorage.setItem(PREVIEW,JSON.stringify(updated));window.dispatchEvent(new Event('afrigo-auth-change'));return updated}if(!firebaseAuth?.currentUser)throw new Error('Authentication required.');const token=await firebaseAuth.currentUser.getIdToken();const response=await fetch('/api/profile/role',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({role})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save role.');window.dispatchEvent(new Event('afrigo-auth-change'));return fromFirebase(firebaseAuth.currentUser)}
export function useAuth(){const[user,setUser]=useState<AuthUser|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{const refresh=()=>{const p=preview();if(p){setUser(p);setLoading(false)}};refresh();window.addEventListener('afrigo-auth-change',refresh);const unsub=firebaseAuth?onAuthStateChanged(firebaseAuth,async value=>{if(!preview())setUser(value?await fromFirebase(value):null);setLoading(false)}):()=>{};if(!isFirebaseConfigured()){setLoading(false)}return()=>{window.removeEventListener('afrigo-auth-change',refresh);unsub()}},[]);const signOut=async()=>{localStorage.removeItem(PREVIEW);if(firebaseAuth)await firebaseSignOut(firebaseAuth);setUser(null)};return useMemo(()=>({user,loading,isSignedIn:Boolean(user&&!user.demo),isDemo:Boolean(user?.demo),setRole:updateRole,createDemo:createDemoSession,signOut,refresh:()=>window.dispatchEvent(new Event('afrigo-auth-change'))}),[user,loading])}
