import { jsonError,requireUser } from '@/lib/serverAuth'
import { requireStaff } from '@/lib/staffAuth'
import { rateLimit } from '@/lib/rateLimit'
const large=()=>Number(process.env.LARGE_PAYOUT_NGN||1000000)
export async function POST(request:Request){try{rateLimit(request,'payout-request',15);const input=await request.json(),action=String(input.action||'request')
 if(action==='request'){const{user,admin,profile}=await requireUser(request);if(user.user_metadata.role!=='Seller')return Response.json({ok:false,error:'Seller role required'},{status:403});if(!profile?.settlement?.recipientCode)return Response.json({ok:false,error:'Add and verify your payout account first'},{status:409});const contractRef=admin.db.collection('contracts').doc(String(input.contractId||'')),contract=await contractRef.get(),data=contract.data();if(!contract.exists||data?.supplierId!==user.id||data?.status!=='completed'||data?.paymentStatus!=='paid')return Response.json({ok:false,error:'Only completed, paid contracts are available for payout'},{status:409});if(['requested','reserved','processing','success','held'].includes(data?.payoutStatus))return Response.json({ok:false,error:'This balance is already reserved or unavailable'},{status:409});const openCases=await admin.db.collection('supportCases').where('contractId','==',contract.id).where('status','==','open').limit(1).get(),amount=Number(data.amount||0),changedBank=Boolean(profile.settlement.verifiedAt&&data.paidAt&&profile.settlement.verifiedAt.toMillis?.()>data.paidAt.toMillis?.()),requiresTwo=!openCases.empty||changedBank||amount>=large(),requestRef=admin.db.collection('payoutRequests').doc(),now=new Date();await admin.db.runTransaction(async transaction=>{transaction.set(requestRef,{contractId:contract.id,sellerId:user.id,amount,currency:data.currency||'NGN',status:openCases.empty?'pending_approval':'held',requiresTwoApprovals:requiresTwo,approvalIds:[],riskReasons:[...(!openCases.empty?['open_dispute']:[]),...(changedBank?['bank_details_changed']:[]),...(amount>=large()?['large_payout']:[])],settlementSnapshot:{accountLast4:profile.settlement.accountLast4,bankCode:profile.settlement.bankCode,recipientCode:profile.settlement.recipientCode},createdAt:now,updatedAt:now});transaction.update(contractRef,{payoutStatus:openCases.empty?'reserved':'held',payoutRequestId:requestRef.id,heldAmount:openCases.empty?0:amount,updatedAt:now})});return Response.json({ok:true,status:openCases.empty?'pending_approval':'held',requiresTwoApprovals:requiresTwo})}
 const{user,admin}=await requireStaff(request,'payouts:execute'),ref=admin.db.collection('payoutRequests').doc(String(input.requestId||'')),snapshot=await ref.get(),data=snapshot.data();if(!snapshot.exists)return Response.json({ok:false,error:'Payout request not found'},{status:404})
 if(action==='approve'){if(!['pending_approval','partially_approved'].includes(data?.status))return Response.json({ok:false,error:'This request is not awaiting approval'},{status:409});const approvals=[...new Set([...(data?.approvalIds||[]),user.id])],required=data?.requiresTwoApprovals?2:1,status=approvals.length>=required?'approved':'partially_approved';await ref.update({approvalIds:approvals,status,updatedAt:new Date(),[`approvalAudit.${user.id}`]:{email:user.email,at:new Date()}});return Response.json({ok:true,status,approvals:approvals.length,required})}
 if(action==='mark_paid'){const externalReference=String(input.externalReference||'').trim().slice(0,180);if(data?.status!=='approved'||!externalReference)return Response.json({ok:false,error:'An approved request and bank/provider reference are required'},{status:409});const contractRef=admin.db.collection('contracts').doc(data.contractId),now=new Date();await admin.db.runTransaction(async transaction=>{transaction.update(ref,{status:'paid',externalReference,markedPaidBy:user.id,markedPaidAt:now,updatedAt:now});transaction.update(contractRef,{payoutStatus:'success',payoutExternalReference:externalReference,paidOutAt:now,updatedAt:now})});return Response.json({ok:true,status:'paid'})}
 return Response.json({ok:false,error:'Unsupported payout action'},{status:400})}catch(error){return jsonError(error)}}
