'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import { useAuth } from '@/lib/auth'

const MotionDiv = motion.div as any
const origins = [{ city: 'Ondo', crop: 'Cocoa', x: '34%', y: '56%' }, { city: 'Kano', crop: 'Sesame', x: '54%', y: '27%' }, { city: 'Kaduna', crop: 'Ginger', x: '48%', y: '39%' }]
const checks = ['Origin verified', 'Supplier verified', 'Grade A', 'Moisture 6.8%', 'Inspection passed']
const demands = [{ place: 'Rotterdam', flag: 'NL', amount: '200 MT' }, { place: 'Hamburg', flag: 'DE', amount: '150 MT' }, { place: 'Dubai', flag: 'AE', amount: '80 MT' }]
const roles = [
  ['01', 'Buyer', 'Publishes verified demand, compares inventory-backed offers, awards contracts and follows payment through delivery.'],
  ['02', 'Seller', 'Lists real lots, adds quotes, accepts awarded contracts, fulfils orders and requests controlled settlement.'],
  ['03', 'Exporter', 'Enters after payment, owns the physical handoff, compliance documents, customs milestones and carrier tracking.'],
]

function Commodity({ small = false }: { small?: boolean }) {
  return <div aria-hidden="true" className={`relative ${small ? 'h-28 w-28' : 'h-48 w-48 sm:h-64 sm:w-64'}`}>
    <div className="absolute inset-[10%] rotate-[-18deg] rounded-[48%_52%_45%_55%/58%_44%_56%_42%] bg-[radial-gradient(circle_at_34%_28%,#f2b66c_0,#9a4f23_28%,#482211_68%,#1b0d08_100%)] shadow-[inset_-20px_-30px_45px_rgba(0,0,0,.45),0_45px_100px_rgba(218,143,57,.18)]" />
    <div className="absolute left-[47%] top-[13%] h-[74%] w-[3px] rotate-[16deg] rounded-full bg-amber-200/30 blur-[1px]" />
    <div className="absolute inset-0 animate-[spin_18s_linear_infinite] rounded-full border border-amber-300/15" />
    <div className="absolute inset-[-12%] animate-[spin_28s_linear_infinite_reverse] rounded-full border border-dashed border-white/10" />
  </div>
}

export default function BusinessHomepage() {
  const { user, isSignedIn, loading } = useAuth()
  const primaryHref = isSignedIn ? (user?.role ? '/dashboard' : '/role-selection') : '/sign-up'
  const primaryLabel = loading ? 'Loading workspace…' : isSignedIn ? (user?.role ? `Open ${user.role} workspace` : 'Choose your trade role') : 'Start trading'

  return <main className="-mx-3 -my-5 overflow-hidden bg-[#07110e] text-[#f6f3e9] sm:-mx-6 lg:-mx-8">
    <section className="relative isolate flex min-h-[calc(100svh-72px)] items-center overflow-hidden px-5 py-20 sm:px-8 lg:px-12">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_48%,rgba(186,112,40,.22),transparent_24%),radial-gradient(circle_at_15%_10%,rgba(28,126,91,.18),transparent_30%)]" />
      <div className="absolute inset-0 opacity-[.12] [background-image:linear-gradient(rgba(255,255,255,.2)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.2)_1px,transparent_1px)] [background-size:72px_72px] [mask-image:linear-gradient(to_bottom,black,transparent_85%)]" />
      <div className="relative mx-auto grid w-full max-w-[1500px] items-center gap-14 lg:grid-cols-[1.08fr_.92fr]">
        <MotionDiv initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .75 }}>
          <p className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.28em] text-[#9ad8bb]"><span className="h-px w-10 bg-[#9ad8bb]" />Africa → World</p>
          <h1 className="mt-7 max-w-5xl text-[clamp(3.7rem,8vw,8.8rem)] font-black leading-[.82] tracking-[-.075em]">African trade.<br/><span className="font-serif font-normal italic text-[#e6b85c]">Without</span> the friction.</h1>
          <p className="mt-8 max-w-2xl text-base leading-7 text-white/60 sm:text-xl sm:leading-8">Afrigo is the controlled infrastructure where verified demand, physical inventory, contracts, payments and cross-border delivery become one accountable record.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href={primaryHref} aria-disabled={loading} className="group inline-flex min-h-14 items-center justify-center gap-4 rounded-full bg-[#e6b85c] px-8 font-black text-[#10251e] transition duration-300 hover:-translate-y-1 hover:bg-[#f4ca73]">{primaryLabel}<span className="transition group-hover:translate-x-1">↗</span></Link><Link href={isSignedIn ? '/onboarding' : '/login'} className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/15 px-8 font-bold text-white/85 transition hover:border-white/35 hover:bg-white/5">{isSignedIn ? 'Verify company' : 'Sign in'}</Link></div>
        </MotionDiv>
        <MotionDiv initial={{ opacity: 0, scale: .88, rotate: -8 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ delay: .15, duration: 1 }} className="relative mx-auto flex aspect-square w-full max-w-xl items-center justify-center">
          <div className="absolute inset-[8%] rounded-full bg-[#d59142]/10 blur-3xl"/><Commodity/><div className="absolute left-0 top-[18%] rounded-2xl border border-white/10 bg-[#10201b]/75 p-4 backdrop-blur-xl"><p className="text-[10px] uppercase tracking-[.22em] text-white/40">Lot identity</p><p className="mt-1 font-mono text-sm text-[#e6b85c]">AFG-COC-260821-0892</p></div><div className="absolute bottom-[13%] right-0 rounded-2xl border border-[#71d7a5]/20 bg-[#10201b]/80 p-4 backdrop-blur-xl"><p className="text-xs font-bold text-[#8ee5b8]">● Inspection passed</p><p className="mt-1 text-xs text-white/45">Ondo, Nigeria · Grade A</p></div>
        </MotionDiv>
      </div><p className="absolute bottom-7 left-1/2 -translate-x-1/2 text-[10px] uppercase tracking-[.28em] text-white/30">Scroll to follow the lot ↓</p>
    </section>

    <section className="border-y border-white/10 bg-[#0a1713] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#70c99d]">01 · Origin</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] sm:text-7xl">Verified<br/>at source.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-white/55">Before a quote becomes a contract, the system connects it to a real Seller, a real company and a specific inventory lot.</p></div><div className="relative min-h-[430px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#10231c] p-6"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_center,#4d8c6e_1px,transparent_1px)] [background-size:18px_18px]"/><div className="absolute left-[18%] top-[12%] h-[75%] w-[62%] bg-[#153f2e] [clip-path:polygon(36%_0,66%_5%,81%_18%,96%_31%,85%_45%,94%_63%,75%_73%,65%_100%,45%_88%,31%_69%,12%_62%,4%_38%,19%_22%)]"/>{origins.map((item,index)=><MotionDiv key={item.city} initial={{opacity:0,scale:.7}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:index*.14}} className="absolute" style={{left:item.x,top:item.y}}><span className="block h-3 w-3 rounded-full bg-[#e6b85c] shadow-[0_0_0_7px_rgba(230,184,92,.13)]"/><div className="mt-3 whitespace-nowrap rounded-xl border border-white/10 bg-[#07110e]/85 px-3 py-2 text-xs backdrop-blur"><b>{item.city}</b><span className="ml-2 text-white/45">{item.crop}</span></div></MotionDiv>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div className="relative flex min-h-[430px] items-center justify-center overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_center,#183c2e,transparent_65%)]"><Commodity small/><span className="absolute top-7 font-mono text-xs tracking-wider text-[#e6b85c]">AFG-COC-260821-0892</span>{checks.map((check,index)=><MotionDiv key={check} initial={{opacity:0,x:index%2?20:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:index*.1}} className={`absolute rounded-full border border-white/10 bg-[#10201b]/90 px-4 py-2 text-xs font-semibold text-[#a5e7c3] ${index===0?'left-4 top-24':index===1?'right-4 top-28':index===2?'left-6 bottom-28':index===3?'right-4 bottom-24':'bottom-6'}`}>✓ {check}</MotionDiv>)}</div><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#70c99d]">02 · Traceability</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] sm:text-7xl">One lot.<br/>One shared truth.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-white/55">Identity, grade, quantity and inspection state follow the product through every authorized handoff—without dashboards pretending that physical events happened.</p></div></div></section>

    <section className="bg-[#e9e4d8] px-5 py-24 text-[#102019] sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#126347]">03 · Marketplace</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_.7fr]"><h2 className="text-5xl font-black tracking-[-.06em] sm:text-7xl">Demand meets verified African supply.</h2><p className="self-end text-lg leading-8 text-[#102019]/60">Buyers publish what they need. Sellers respond from actual inventory. Every accepted offer progresses through a controlled commercial lifecycle.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{demands.map((d,index)=><MotionDiv key={d.place} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.12}} className="group rounded-[1.75rem] border border-[#102019]/15 bg-[#f7f4ec] p-6 transition hover:-translate-y-2 hover:shadow-2xl"><div className="flex items-center justify-between"><span className="rounded-full bg-[#102019] px-3 py-1 font-mono text-xs text-white">{d.flag}</span><span className="text-sm text-[#102019]/45">Open RFQ ↗</span></div><p className="mt-16 text-3xl font-black">{d.amount}</p><p className="mt-1 text-[#102019]/60">Grade A cocoa · {d.place}</p></MotionDiv>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#70c99d]">04 · Contract</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] sm:text-7xl">Trust, made operational.</h2></div><p className="self-end text-lg leading-8 text-white/55">The system recognizes who is Buyer, Seller, Exporter or operational staff—and authorizes each mutation server-side.</p></div><div className="mt-16 flex flex-col gap-3 lg:flex-row lg:items-center">{['RFQ','Inventory-backed bid','Contract','Payment verified','Exporter assigned'].map((item,index)=><div key={item} className="contents"><MotionDiv initial={{opacity:0,scale:.92}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:index*.1}} className="flex min-h-28 flex-1 items-center justify-center rounded-2xl border border-white/10 bg-white/[.035] px-5 text-center font-bold">{item}</MotionDiv>{index<4&&<span className="rotate-90 self-center text-[#e6b85c] lg:rotate-0">→</span>}</div>)}</div></div></section>

    <section className="border-y border-white/10 bg-[#0d1d18] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[#70c99d]">05 · Export</p><h2 className="mt-5 text-5xl font-black tracking-[-.055em] sm:text-7xl">The Exporter enters after payment.</h2><p className="mt-6 text-lg leading-8 text-white/55">The Exporter does not buy or sell. They receive a funded contract, coordinate pickup and compliance, then record the physical journey to destination.</p></div><div className="rounded-[2rem] border border-white/10 bg-[#07110e] p-7 sm:p-10"><div className="flex items-center justify-between"><span className="font-mono text-xs text-white/45">SHIPMENT AFG-SHP-20481</span><span className="rounded-full bg-[#e6b85c]/15 px-3 py-1 text-xs font-bold text-[#e6b85c]">IN TRANSIT</span></div><div className="relative mt-16 h-24"><div className="absolute left-2 right-2 top-3 h-px bg-white/15"/><MotionDiv initial={{width:'0%'}} whileInView={{width:'76%'}} viewport={{once:true}} transition={{duration:1.4}} className="absolute left-2 top-3 h-px bg-[#e6b85c]"/><div className="absolute left-0 top-0 h-7 w-7 rounded-full border-4 border-[#07110e] bg-[#e6b85c]"/><div className="absolute left-[48%] top-0 h-7 w-7 rounded-full border-4 border-[#07110e] bg-[#e6b85c]"/><div className="absolute right-0 top-0 h-7 w-7 rounded-full border-4 border-[#07110e] bg-white/20"/><div className="absolute left-0 top-12 text-xs"><b>Badagry</b><br/><span className="text-white/40">Origin</span></div><div className="absolute left-[43%] top-12 text-xs"><b>Lagos Port</b><br/><span className="text-white/40">Customs cleared</span></div><div className="absolute right-0 top-12 text-right text-xs"><b>Rotterdam</b><br/><span className="text-white/40">Destination</span></div></div></div></div></section>

    <section className="bg-[#f3efe5] px-5 py-24 text-[#102019] sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#126347]">The accountable network</p><div className="mt-12 divide-y divide-[#102019]/15 border-y border-[#102019]/15">{roles.map(([number,name,text])=><div key={name} className="grid gap-4 py-8 md:grid-cols-[80px_220px_1fr] md:items-center"><span className="font-mono text-sm text-[#126347]">{number}</span><h3 className="text-3xl font-black">{name}</h3><p className="max-w-2xl leading-7 text-[#102019]/60">{text}</p></div>)}</div></div></section>

    <section className="relative px-5 py-28 text-center sm:px-8 lg:px-12 lg:py-44"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(35,122,88,.2),transparent_55%)]"/><div className="relative mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#70c99d]">06 · Destination</p><h2 className="mt-6 text-5xl font-black leading-[.94] tracking-[-.06em] sm:text-8xl">From African origin<br/><span className="font-serif font-normal italic text-[#e6b85c]">to global opportunity.</span></h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-white/55">Enter Afrigo through the workspace built for your responsibility. Your identity and contract participation determine what happens next.</p><Link href={primaryHref} className="group mt-10 inline-flex min-h-16 items-center justify-center gap-5 rounded-full bg-[#e6b85c] px-10 font-black text-[#10251e] transition hover:-translate-y-1 hover:bg-[#f4ca73]">Trade through Afrigo <span className="transition group-hover:translate-x-1">→</span></Link></div></section>

    <footer className="border-t border-white/10 px-5 py-8 text-sm text-white/40 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Afrigo · Controlled African trade infrastructure</p><nav className="flex flex-wrap gap-5"><Link href="/privacy" className="hover:text-white">Privacy</Link><Link href="/terms" className="hover:text-white">Terms</Link><Link href="/login" className="hover:text-white">Account access</Link></nav></div></footer>
  </main>
}
