'use client'
import { useEffect,useRef,useState } from 'react'
import { collection,limit,onSnapshot,orderBy,query } from 'firebase/firestore'
import { motion } from 'framer-motion'
import { authenticatedFetch } from '@/lib/apiClient'
import { firebaseAuth,firebaseDb } from '@/lib/firebaseClient'
const MotionDiv=motion.div as any

type Message={id:string;senderId:string;senderName:string;senderRole:string;message:string;createdAt?:any}
export default function ContractChat({contract,onClose}:{contract:any;onClose:()=>void}){
 const[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false),[sending,setSending]=useState(false),bottom=useRef<HTMLDivElement>(null)
 useEffect(()=>{let unsubscribe=()=>{};void(async()=>{try{await authenticatedFetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'open-chat',contractId:contract.id})});if(!firebaseDb)throw new Error('Real-time messaging is not configured.');const stream=query(collection(firebaseDb,'conversations',contract.id,'messages'),orderBy('createdAt','asc'),limit(100));unsubscribe=onSnapshot(stream,snapshot=>{setMessages(snapshot.docs.map(document=>({id:document.id,...document.data()} as Message)));setReady(true)},cause=>setError(cause.message))}catch(cause:any){setError(cause.message)}})();return()=>unsubscribe()},[contract.id])
 useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages.length])
 const send=async(event:React.FormEvent)=>{event.preventDefault();const message=text.trim();if(!message)return;setSending(true);setError('');try{await authenticatedFetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'message',contractId:contract.id,message})});setText('')}catch(cause:any){setError(cause.message)}finally{setSending(false)}}
 return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label="Contract conversation"><MotionDiv initial={{opacity:0,y:30,scale:.98}} animate={{opacity:1,y:0,scale:1}} className="flex h-[88vh] w-full max-w-2xl flex-col overflow-hidden rounded-t-[2rem] bg-white shadow-2xl sm:h-[76vh] sm:rounded-[2rem]">
  <header className="flex items-center justify-between border-b bg-[var(--afrigo-primary-green)] p-5 text-white"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/70">Live contract chat</p><h2 className="mt-1 text-lg font-black">Contract {contract.id.slice(0,8)}</h2></div><button onClick={onClose} aria-label="Close chat" className="rounded-full bg-white/15 px-3 py-2 text-lg transition hover:bg-white/25">×</button></header>
  <div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-4 sm:p-6">{!ready&&!error&&<p className="text-center text-sm text-slate-500">Connecting securely…</p>}{ready&&!messages.length&&<div className="mx-auto mt-12 max-w-sm text-center"><p className="text-3xl">💬</p><p className="mt-3 font-bold text-slate-800">Start the conversation</p><p className="mt-1 text-sm text-slate-500">Buyer, Seller, and the assigned Exporter can communicate here in real time.</p></div>}{messages.map(item=>{const mine=item.senderId===firebaseAuth?.currentUser?.uid;return <MotionDiv initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} key={item.id} className={`flex ${mine?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 shadow-sm ${mine?'rounded-br-md bg-[var(--afrigo-primary-green)] text-white':'rounded-bl-md border bg-white text-slate-900'}`}><div className={`mb-1 flex gap-2 text-[11px] font-bold ${mine?'text-white/70':'text-slate-500'}`}><span>{mine?'You':item.senderName||item.senderRole}</span><span>{item.senderRole}</span></div><p className="whitespace-pre-wrap break-words text-sm">{item.message}</p><p className={`mt-1 text-right text-[10px] ${mine?'text-white/60':'text-slate-400'}`}>{item.createdAt?.toDate?.()?.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})||'Sending…'}</p></div></MotionDiv>})}<div ref={bottom}/></div>
  {error&&<p role="alert" className="border-t bg-red-50 px-5 py-2 text-sm text-red-700">{error}</p>}<form onSubmit={send} className="flex gap-2 border-t bg-white p-3 sm:p-4"><textarea required rows={1} maxLength={2000} value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();event.currentTarget.form?.requestSubmit()}}} placeholder="Write a message…" className="max-h-28 min-h-12 flex-1 resize-none rounded-2xl border bg-slate-50 px-4 py-3 outline-none focus:border-[var(--afrigo-primary-green)]"/><button disabled={sending||!text.trim()} className="rounded-2xl bg-[var(--afrigo-primary-green)] px-5 font-bold text-white transition hover:-translate-y-0.5 disabled:opacity-50">{sending?'…':'Send'}</button></form>
 </MotionDiv></div>
}
