'use client'
import { useState } from 'react'
import { authenticatedFetch } from '@/lib/apiClient'
export default function SellerPayoutPanel({data,reload}:{data:any;reload:()=>Promise<void>}){
 const[editing,setEditing]=useState(!data?.settlement?.verified),[account,setAccount]=useState(''),[bank,setBank]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy('account');setMessage('');try{await authenticatedFetch('/api/settlement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountNumber:account,bankCode:bank})});setMessage('Payout account verified successfully.');setEditing(false);setAccount('');await reload()}catch(error:any){setMessage(error.message)}finally{setBusy('')}}
 const request=async(contractId:string)=>{setBusy(contractId);setMessage('');try{const result=await authenticatedFetch('/api/payout-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request',contractId})});setMessage(result.status==='held'?'Request recorded but held for dispute review.':'Payout requested and balance reserved for approval.');await reload()}catch(error:any){setMessage(error.message)}finally{setBusy('')}}
 const eligible=(data?.contracts||[]).filter((item:any)=>item.status==='completed'&&item.paymentStatus==='paid'&&!['reserved','held','processing','success'].includes(item.payoutStatus))
 return <section className="mt-6 overflow-hidden rounded-3xl border bg-gradient-to-br from-emerald-50 to-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Seller earnings</p><h3 className="mt-1 text-xl font-black">Payout account and requests</h3><p className="mt-1 text-sm text-slate-600">Completed orders become available here. Requests reserve the balance immediately.</p></div>{data?.settlement?.verified&&<button onClick={()=>setEditing(value=>!value)} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">{editing?'Cancel':'Change account'}</button>}</div>
  {editing?<form onSubmit={save} className="grid gap-3 p-5 sm:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-bold">Account number<input required inputMode="numeric" minLength={8} value={account} onChange={event=>setAccount(event.target.value.replace(/\D/g,''))} placeholder="0123456789" className="mt-2 w-full rounded-xl border bg-white px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Paystack bank code<input required value={bank} onChange={event=>setBank(event.target.value.trim())} placeholder="e.g. 058" className="mt-2 w-full rounded-xl border bg-white px-4 py-3 font-normal"/></label><button disabled={busy==='account'} className="self-end rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy==='account'?'Verifying…':'Verify account'}</button></form>:<div className="p-5"><div className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-800"><span>✓</span> Verified account ending {data?.settlement?.accountLast4}</div></div>}
  <div className="grid gap-3 border-t p-5">{eligible.map((item:any)=><div key={item.id} className="flex flex-col gap-3 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{item.productTitle||`Contract ${item.id.slice(0,8)}`}</p><p className="text-sm text-slate-600">{item.currency||'NGN'} {Number(item.amount||0).toLocaleString()} available</p></div><button disabled={!data?.settlement?.verified||!!busy} onClick={()=>void request(item.id)} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Request payout</button></div>)}{!eligible.length&&<p className="rounded-2xl bg-white p-4 text-sm text-slate-600">No completed, paid balance is currently available for a new request.</p>}</div>
  {message&&<p role="status" className="border-t bg-white px-5 py-3 text-sm font-semibold text-slate-700">{message}</p>}
 </section>
}
