'use client'
import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { authenticatedFetch } from '@/lib/apiClient'
import type { Role } from '@/lib/roles'
import ContractChat from './ContractChat'
import ChatInbox from './ChatInbox'
import MessagingBoundary from './MessagingBoundary'
const MotionSection = motion.section as any
const button='rounded-xl border border-[var(--afrigo-border)] px-3 py-2 text-sm font-semibold transition hover:-translate-y-0.5 hover:border-[var(--afrigo-primary-green)] disabled:opacity-40'

export default function TradeOperations({role}:{role:Role}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[exporter,setExporter]=useState<Record<string,string>>({}),[tracking,setTracking]=useState<Record<string,string>>({}),[chat,setChat]=useState<any>(null)
 const load=async()=>{try{setError('');setData(await authenticatedFetch('/api/dashboard'))}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[role])
 const filtered=useMemo(()=>((data?.rfqs||[]) as any[]).filter(item=>String(item.title||'').toLowerCase().includes(search.toLowerCase())),[data,search]),rfqs=filtered.slice(page*10,page*10+10)
 const request=async(key:string,url:string,body?:any)=>{setBusy(key);try{const result=await authenticatedFetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load();return result}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const act=async(action:string,contractId:string)=>{const needs=['cancel','dispute','refund','milestone'].includes(action),value=needs?prompt(action==='milestone'?'New fulfilment milestone':`Reason for ${action}`)||'':'';if(needs&&!value)return;await request(contractId+action,'/api/operations',{action,contractId,reason:value,milestone:value})}
 const pay=async(id:string)=>{setBusy(id+'pay');try{const result=await authenticatedFetch('/api/payments/initialize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractId:id})});location.assign(result.authorizationUrl)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const settle=async()=>{const accountNumber=prompt('Settlement account number'),bankCode=accountNumber&&prompt('Paystack bank code');if(accountNumber&&bankCode)await request('settlement','/api/settlement',{accountNumber,bankCode})}
 const track=async(id:string)=>{setBusy(id+'track');try{const result=await authenticatedFetch(`/api/logistics/track?shipmentId=${encodeURIComponent(id)}`),shipment=result.data?.shipments?.[0],event=shipment?.events?.[0];setTracking(v=>({...v,[id]:event?.description||shipment?.status?.statusCode||'Tracking received'}))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const milestone=async(id:string)=>{const status=prompt('Milestone: Picked Up, In Transit, Customs Clearance, Cleared, or Delivered'),trackingNumber=prompt('Carrier tracking number (optional)')||'';if(status)await request(id+'ship','/api/shipments/milestone',{shipmentId:id,status,trackingNumber,carrier:'DHL'})}
 const openContractChat=async(item:any)=>{const result=await request(item.id+'chat','/api/conversations',{action:'open-contract',contractId:item.id});if(result?.conversation)setChat(result.conversation)}
 const inquire=async(item:any)=>{const result=await request(item.id+'inquiry','/api/conversations',{action:'open-rfq',rfqId:item.id});if(result?.conversation)setChat(result.conversation)}
 const setChatContract=(item:any)=>void openContractChat(item)
 const purchase=async(item:any)=>{const entered=prompt(`How many ${item.unit||'units'} of ${item.title} do you want to reserve?`,`1`),quantity=Number(entered);if(!entered||!Number.isFinite(quantity)||quantity<=0)return;const result=await request(item.id+'purchase','/api/purchases',{lotId:item.id,quantity});if(result?.contractId)setNotice('Purchase reserved. The Seller must accept the contract before secure payment becomes available.')}
 const sellerInquiryPanel=role==='Seller'&&rfqs.some(item=>item.status==='Open')?<div className="mt-4 rounded-2xl border border-dashed p-4"><p className="text-sm font-bold">Pre-contract inquiries</p><p className="mb-3 text-xs text-slate-500">Ask the Buyer a question before submitting or updating a bid.</p><div className="flex flex-wrap gap-2">{rfqs.filter(item=>item.status==='Open').map(item=><button key={`inquiry-${item.id}`} disabled={!!busy} onClick={()=>void inquire(item)} className={button}>Ask Buyer: {item.title}</button>)}</div></div>:null
 const marketplacePanel=role==='Buyer'?<div className="mt-7"><div><h3 className="font-bold">Live Seller marketplace</h3><p className="text-xs text-slate-500">Inventory is reserved transactionally when you create a purchase.</p></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{(data?.marketplace||[]).map((item:any)=><div key={item.id} className="rounded-2xl border bg-white p-4 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex justify-between gap-3"><span className="font-bold">{item.title}</span><span className="text-sm font-semibold">{item.currency||'NGN'} {Number(item.price).toLocaleString()}/{item.unit||'unit'}</span></div><p className="mt-1 text-sm text-slate-500">{Number(item.quantity).toLocaleString()} {item.unit||'units'} available {item.origin?`· ${item.origin}`:''}</p><button disabled={!!busy} onClick={()=>void purchase(item)} className={`${button} mt-3 bg-[var(--afrigo-primary-green)] text-white`}>Reserve and purchase</button></div>)}{!(data?.marketplace||[]).length&&<p className="text-sm text-slate-500">No Seller inventory is currently available.</p>}</div></div>:null
 if(error&&!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>
 return <MotionSection initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="rounded-3xl border border-[var(--afrigo-border)] bg-white p-5 shadow-xl sm:p-8">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--afrigo-secondary-gold)]">Live operations</p><h2 className="mt-2 text-2xl font-black text-[var(--afrigo-primary-green)]">{role} workspace records</h2></div><div className="flex gap-2">{role==='Seller'&&<button onClick={settle} className={button}>Set payout account</button>}{(role==='Buyer'||role==='Seller')&&<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Search RFQs" className="min-w-0 rounded-xl border px-4 py-2"/>}</div></div>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  {notice&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
  <MessagingBoundary><ChatInbox/></MessagingBoundary>
  {sellerInquiryPanel}
  {marketplacePanel}
  {role==='Seller'&&data?.metrics&&<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Bids',data.metrics.totalBids],['Win rate',`${data.metrics.winRate}%`],['Completed',data.metrics.completedContracts],['Verified revenue',Number(data.metrics.revenue).toLocaleString()]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-[var(--afrigo-bg)] p-4"><p className="text-xs text-[var(--afrigo-text-secondary)]">{label}</p><p className="mt-1 text-xl font-black text-[var(--afrigo-primary-green)]">{value}</p></div>)}</div>}
  {(role==='Buyer'||role==='Seller')&&<div className="mt-6"><h3 className="font-bold">RFQs</h3><div className="mt-3 grid gap-3">{rfqs.map(item=><div key={item.id} className="rounded-xl bg-[var(--afrigo-bg)] p-4"><div className="flex justify-between gap-3"><span className="font-semibold">{item.title}</span><span className="text-sm">{item.status}</span></div><p className="text-sm text-[var(--afrigo-text-secondary)]">{item.quantity} {item.unit} · {item.destination_country}</p></div>)}{!rfqs.length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No matching RFQs.</p>}</div><div className="mt-3 flex gap-2"><button disabled={!page} onClick={()=>setPage(v=>v-1)} className={button}>Previous</button><button disabled={filtered.length<=(page+1)*10} onClick={()=>setPage(v=>v+1)} className={button}>Next</button></div></div>}
  <div className="mt-7"><h3 className="font-bold">Contracts and payments</h3><div className="mt-3 grid gap-3">{(data?.contracts||[]).map((item:any)=><div key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold">Contract {item.id.slice(0,8)}</span><span className="rounded-full bg-[var(--afrigo-primary-green-light)] px-3 py-1 text-xs font-bold text-white">{item.status}</span></div><p className="mt-2 text-sm">{item.currency} {Number(item.amount||0).toLocaleString()} · Payment: {item.paymentStatus||'not started'} · Payout: {item.payoutStatus||'pending'}</p><div className="mt-3 flex flex-wrap gap-2">{role==='Buyer'&&item.status==='accepted'&&<button disabled={!!busy} onClick={()=>pay(item.id)} className={button}>Pay securely</button>}{role==='Buyer'&&item.status==='paid'&&<><select value={exporter[item.id]||''} onChange={e=>setExporter(v=>({...v,[item.id]:e.target.value}))} className={button}><option value="">Choose verified Exporter</option>{(data.exporters||[]).map((x:any)=><option key={x.id} value={x.id}>{x.displayName}{x.country?` · ${x.country}`:''}</option>)}</select><button disabled={!exporter[item.id]||!!busy} onClick={()=>request(item.id+'assign','/api/operations',{action:'assign-exporter',contractId:item.id,exporterId:exporter[item.id]})} className={button}>Assign</button></>}{role==='Seller'&&item.status==='pending'&&<button onClick={()=>act('accept',item.id)} className={button}>Accept contract</button>}{role==='Seller'&&['accepted','paid','fulfilling'].includes(item.status)&&<button onClick={()=>act('milestone',item.id)} className={button}>Update milestone</button>}<button onClick={()=>setChatContract(item)} className={`${button} bg-slate-900 text-white`}>Open live chat</button>{['pending','accepted'].includes(item.status)&&<button onClick={()=>act('cancel',item.id)} className={button}>Cancel</button>}<button onClick={()=>act('dispute',item.id)} className={button}>Dispute</button>{role==='Buyer'&&['paid','disputed'].includes(item.status)&&<button onClick={()=>act('refund',item.id)} className={button}>Request refund</button>}</div></div>)}{!(data?.contracts||[]).length&&<p className="text-sm text-[var(--afrigo-text-secondary)]">No contracts yet.</p>}</div></div>
  {!!(data?.shipments||[]).length&&<div className="mt-7"><h3 className="font-bold">Shipments</h3><div className="mt-3 grid gap-3">{data.shipments.map((item:any)=><div key={item.id} className="rounded-2xl border p-4"><div className="flex justify-between"><span className="font-semibold">Shipment {item.id.slice(0,8)}</span><span>{item.status}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[var(--afrigo-primary-green)] transition-all" style={{width:`${item.progress||0}%`}}/></div><div className="mt-3 flex gap-2">{role==='Exporter'?<button onClick={()=>milestone(item.id)} className={button}>Update shipment</button>:<button onClick={()=>track(item.id)} className={button}>Track with DHL</button>}</div>{tracking[item.id]&&<p className="mt-2 text-sm">{tracking[item.id]}</p>}</div>)}</div></div>}
  {chat&&<ContractChat conversation={chat} onClose={()=>setChat(null)}/>}
 </MotionSection>
}
